version: '3'

services:
  server:
    build: .
    command: cargo run
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://root@database/sc_predictions
      DBMIGRATE_URL: postgres://root@database/sc_predictions
      DBMIGRATE_PATH: ./migrations
      CLIENT_HOST: http://localhost:3000
      RUST_BACKTRACE: full
      RUST_LOG: actix_web=debug
    links:
      - database
  database:
    image: "postgres:10.5"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ''
      POSTGRES_DB: sc_predictions