version: "3"

services:
  # server:
  #   build: .
  #   command: cargo run --bin server
  #   volumes:
  #     - .:/app
  #   ports:
  #     - '8080:8080'
  #   environment:
  #     DATABASE_URL: postgres://root@database/sc_predictions
  #     CLIENT_HOST: http://localhost:3000
  #     RUST_BACKTRACE: full
  #     RUST_LOG: actix_web=debug
  #
  #   links:
  #     - database
  database:
    image: "postgres:10.5"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: sc_predictions
      POSTGRES_PASSWORD: abc123
    volumes:
      - ./seeds:/seeds
    networks:
      - sc-predictions

networks:
  sc-predictions:
    name: sc-predictions
    ipam:
      driver: default
      config:
        - subnet: "10.16.101.0/24"