name: Rust

on:
  push:
    branches: [ release ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --bin server --verbose --release
    - name: set deploy key
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${DEPLOY_KEY}"
    - name: copy build
      run: scp target/release/server ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.TARGET_FOLDER }}/server-new
        
